//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSocietyWebServices
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    [DataContract(IsReference = true)]
    public partial class FEED
    {
        [DataMember(Order = 1)]
        public int FeedID { get; set; }
        [DataMember(Order = 2)]
        public string DateCreated { get; set; }
        [DataMember(Order = 3)]
        public string TimeCreated { get; set; }
        [DataMember(Order = 4)]
        public Nullable<int> Title { get; set; }
        [DataMember(Order = 5)]
        public Nullable<int> UserID { get; set; }
        [DataMember(Order = 6)]
        public Nullable<int> PetID { get; set; }
        [DataMember(Order = 7)]
        public Nullable<int> EventID { get; set; }
        [DataMember(Order = 8)]
        public Nullable<int> StrayID { get; set; }
        [DataMember(Order = 9)]
        public Nullable<int> LocationID { get; set; }
        [DataMember(Order = 10)]
        public Nullable<int> ReviewID { get; set; }
        [DataMember(Order = 11)]
        public Nullable<int> LostID { get; set; }
        [DataMember(Order = 12)]
        public string Action { get; set; }
    }
}
