//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSocietyWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEED
    {
        public int FeedID { get; set; }
        public string DateCreated { get; set; }
        public string TimeCreated { get; set; }
        public Nullable<int> Title { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PetID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> StrayID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<int> LostID { get; set; }
        public string Action { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual USER USER { get; set; }
        public virtual PET PET { get; set; }
        public virtual STRAY STRAY { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual REVIEW REVIEW { get; set; }
        public virtual LOST LOST { get; set; }
    }
}
