//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSocietyWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.PINs = new HashSet<PIN>();
            this.REVIEWs = new HashSet<REVIEW>();
            this.PINs = new HashSet<PIN>();
        }
    
        public int LocationID { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public string DateCreated { get; set; }
        public string TimeCreated { get; set; }
        public Nullable<int> PinID { get; set; }
        public int UserID { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ICollection<PIN> PINs { get; set; }
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
    }
}
