//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSocietyWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOST
    {
        public LOST()
        {
            this.FEEDs = new HashSet<FEED>();
        }
    
        public int LostID { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Found { get; set; }
        public string Reward { get; set; }
        public Nullable<int> PetID { get; set; }
    
        public virtual ICollection<FEED> FEEDs { get; set; }
        public virtual PET PET { get; set; }
    }
}
