//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSocietyWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.PETs = new HashSet<PET>();
            this.LOCATIONs = new HashSet<LOCATION>();
            this.EVENTs = new HashSet<EVENT>();
            this.ATTENDEEs = new HashSet<ATTENDEE>();
            this.LOSTs = new HashSet<LOST>();
            this.REVIEWs = new HashSet<REVIEW>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Biography { get; set; }
        public string Privicy { get; set; }
        public string Sex { get; set; }
        public string Contact { get; set; }
        public string Credibility { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public Nullable<int> ProfileImageID { get; set; }
        public Nullable<int> PinID { get; set; }
    
        public virtual ICollection<PET> PETs { get; set; }
        public virtual ICollection<LOCATION> LOCATIONs { get; set; }
        public virtual ICollection<EVENT> EVENTs { get; set; }
        public virtual ICollection<ATTENDEE> ATTENDEEs { get; set; }
        public virtual ICollection<LOST> LOSTs { get; set; }
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
    }
}
